output   = "db/public"
pkgname  = "dbpublic"
add-global-variants = true
wipe     = true
no-tests = true
add-enum-types = true

[psql]
dbname = "iot"
host   = "localhost"
port   = 60001
user   = "postgres"
pass   = "secret"
schema = "public"
sslmode = "disable"
whitelist = [
    "asset", "heap", "trend_0", "trend_agg", "pipeline",
    "asset_type", "attribute_schema",
    "dashboard", "widget", "widget_element", "widget_type",
    "eliona_app",
    "alarm", "alarm_cfg", "alarm_history",
    "edge_bridge", "eliona_node", "iosys_access", "iosys_device", "mbus_access", "mbus_device"
]

[[types]]
[types.match]
type = "null.Int"
nullable = true

[types.replace]
type = "null.Int32"

[[types]]
[types.match]
type = "int"

[types.replace]
type = "int32"

[aliases.tables.alarm_cfg]
up_plural     = "AlarmConfigs"
up_singular   = "AlarmConfig"
down_plural   = "alarmConfigs"
down_singular = "alarmConfig"