/*
 * Hailo app API
 *
 * API to access and configure the Hailo app
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// DataSubtype : Type of asset data
type DataSubtype string

// List of DataSubtype
const (
	SUBTYPE_INPUT  DataSubtype = "input"
	SUBTYPE_INFO   DataSubtype = "info"
	SUBTYPE_STATUS DataSubtype = "status"
	SUBTYPE_OUTPUT DataSubtype = "output"
)

// AssertDataSubtypeRequired checks if the required fields are not zero-ed
func AssertDataSubtypeRequired(obj DataSubtype) error {
	return nil
}

// AssertRecurseDataSubtypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DataSubtype (e.g. [][]DataSubtype), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDataSubtypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDataSubtype, ok := obj.(DataSubtype)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDataSubtypeRequired(aDataSubtype)
	})
}
